-- Auto-generated seed SQL
BEGIN;

-- Vai trò ADMIN
INSERT INTO vai_tro (ma_vai_tro, ten_vai_tro, mo_ta, cap_do, trang_thai, ngay_tao)
VALUES ('ADMIN', 'Quản trị viên', 'Toàn quyền hệ thống', 100, true, NOW())
ON CONFLICT (ma_vai_tro) DO NOTHING;

-- Admin user
INSERT INTO nguoi_dung (ten_dang_nhap, mat_khau, email, ho_ten, trang_thai, ngay_tao, ngay_cap_nhat)
VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'admin@company.com', 'Administrator', 'HOAT_DONG', NOW(), NOW())
ON CONFLICT (ten_dang_nhap) DO NOTHING;

-- Gán vai trò ADMIN
INSERT INTO nguoi_dung_vai_tro (nguoi_dung_id, vai_tro_id)
SELECT n.id, v.id FROM nguoi_dung n, vai_tro v WHERE n.ten_dang_nhap = 'admin' AND v.ma_vai_tro = 'ADMIN'
ON CONFLICT DO NOTHING;

-- Phòng ban
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('KT', 'Kế toán', 'Phòng Kế toán - Tài chính', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('MKT', 'Marketing', 'Phòng Kinh doanh và Marketing', '08:30', '17:30', 10, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('DH', 'Đơn hàng', 'Phòng Quản lý đơn hàng', '07:30', '16:30', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('KV', 'Kho vận', 'Phòng Kho vận - Logistics', '06:00', '15:00', 10, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('CH', 'Chia hàng', 'Bộ phận Chia hàng', '06:00', '15:00', 10, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('NS', 'Nhân Sự', 'Phòng Nhân Sự', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('SHIP', 'Giao Hàng', '', '04:00', '16:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('KE_TOAN', 'Kế Toán', 'Phòng Kế Toán', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('KINH_DOANH', 'Kinh Doanh', 'Phòng Kinh Doanh', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('GIAO_HANG', 'Giao hàng', 'Phòng Giao hàng', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('TM', 'Thu mua', '', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO NOTHING;

-- Nhân viên
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0001', 'ĐỖ MỘNG CHÚC ANH', NULL, NULL, 'Thủ quỹ', 6400000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KE_TOAN'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0002', 'LÊ THÀNH HOÀNG', 'hoang@mail.com', NULL, '', 5000000, '2026-01-13', 'NGHI_VIEC', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KE_TOAN'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0003', 'LÂM NHƯ NGỌC', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KE_TOAN'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0004', 'PHẠM THÚY DUY', 'duy@mail.com', NULL, '', 5000000, '2026-01-13', 'NGHI_VIEC', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KE_TOAN'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0005', 'NGUYỄN ÁI MINH TRIỆU', NULL, NULL, 'Nhân viên', 5500000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KINH_DOANH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0006', 'NGUYỄN THỊ THANH THÚY', NULL, NULL, 'Nhân viên', 5500000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KINH_DOANH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0007', 'PHẠM MINH MẪN', NULL, NULL, 'Nhân viên', 4000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'DH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0008', 'LÂM HUỲNH THẠCH QUÝ', NULL, NULL, 'Nhân viên', 4000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'DH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0009', 'NGUYỄN ÁI KHANH', NULL, NULL, 'Nhân viên', 4000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'DH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0010', 'NGUYỄN VŨ HOÀNG', NULL, NULL, 'Trưởng nhóm', 6000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'DH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0011', 'TRẦN THỊ DIỆU LINH', NULL, NULL, 'Nhân viên', 5000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KE_TOAN'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0012', 'TRẦN HỒ HỮU NHÂN', 'nhan@mail.com', NULL, '', 5000000, '2026-01-13', 'NGHI_VIEC', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KV'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0013', 'TRẦN THỊ TUYẾT LÊ', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0014', 'DƯ THỊ ƯƠNG', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0015', 'SƠN THỊ NGỌC HUYỀN', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0016', 'VÕ THỊ BÍCH DUNG', NULL, NULL, 'Quản Lý', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KV'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0017', 'TRẦN THỊ THANH HƯƠNG', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0018', 'TRẦN THỊ NGỌC THANH', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0019', 'BÙI THỊ ÁI VÂN', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0020', 'NGUYỄN THỊ THU', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0021', 'PHẠM THỊ MINH', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0022', 'CHÂU THỊ BÉ', 'be@mail.com', NULL, '', 5000000, '2026-01-13', 'NGHI_VIEC', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0023', 'NGUYỄN NGỌC KIM VĂN', 'van@mail.com', NULL, '', 5000000, '2026-01-13', 'NGHI_VIEC', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0024', 'LÊ THỊ THÙY TRANG', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0025', 'NGUYỄN LÝ HỒNG NGỌC', NULL, NULL, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0026', 'NGUYỄN NHẬT TUẤN', NULL, NULL, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'GIAO_HANG'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0027', 'PHẠM NGỌC AN', NULL, NULL, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'GIAO_HANG'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0028', 'HOÀNG HÙNG', NULL, NULL, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'GIAO_HANG'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0029', 'TRẦN ĐỨC TÚ', NULL, NULL, 'Nhân viên', 4500000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'GIAO_HANG'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0030', 'TRẦN QUỐC VŨ', NULL, NULL, 'Nhân viên', 5500000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'TM'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0032', 'NGUYỄN THÀNH BẢO', NULL, NULL, 'Nhân Viên', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'KV'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0033', 'LÝ VĂN HÒA', NULL, NULL, 'Nhân viên', 4500000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'GIAO_HANG'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0034', 'HUỲNH PHƯỚC HẢI', NULL, NULL, 'Nhân viên', 4500000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'GIAO_HANG'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0035', 'TRẦN THỊ ÁI NHI', NULL, NULL, 'Học việc', 3500000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'MKT'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0036', 'TRƯƠNG MỸ DUYÊN', NULL, NULL, 'Học việc', 3500000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'MKT'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0037', 'LÊ PHẠM HÀ', NULL, NULL, 'Sơ chế', 4550000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'CH'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0038', 'PHẠM VĂN HÙNG', NULL, NULL, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'TM'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, phong_ban_id, ngay_tao, ngay_cap_nhat) VALUES ('NV0039', 'HOÀNG TỬ LẬP', NULL, NULL, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', (SELECT id FROM phong_ban WHERE ma_phong_ban = 'TM'), NOW(), NOW()) ON CONFLICT (ma_nhan_vien) DO NOTHING;

-- Khoản lương
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('LUONG_CO_BAN', 'Lương cơ bản', 'THU_NHAP', true, NULL, '', 1, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('THUONG_HIEU_SUAT', 'Thưởng hiệu suất', 'THU_NHAP', true, NULL, '', 2, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('PHU_CAP_XANG_XE', 'Phụ cấp xăng xe', 'THU_NHAP', false, NULL, '', 3, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('PHU_CAP_DIEN_THOAI', 'Phụ cấp điện thoại', 'THU_NHAP', false, NULL, '', 4, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('HO_TRO_CHUYEN_CAN', 'Hỗ trợ chuyên cần', 'THU_NHAP', false, NULL, '', 5, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('HO_TRO_AN_CA', 'Hỗ trợ ăn ca', 'THU_NHAP', false, NULL, '', 6, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('THUONG_KINH_DOANH', 'Thưởng kinh doanh', 'THU_NHAP', true, NULL, '', 7, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('PHU_CAP_KHAC', 'Phụ cấp khác', 'THU_NHAP', false, NULL, '', 8, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('PHU_CAP_CHUC_VU', 'Phụ cấp chức vụ', 'THU_NHAP', true, NULL, '', 9, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('PHU_CAP_THAM_NIEN', 'Phụ cấp thâm niên', 'THU_NHAP', true, NULL, '', 10, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('BHXH_NV', 'BHXH/BHYT/BHTN (NV đóng)', 'KHAU_TRU', false, NULL, '', 100, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('BHXH_NLD', 'BHXH (8%)', 'KHAU_TRU', false, NULL, '', 101, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('BHYT_NLD', 'BHYT (1.5%)', 'KHAU_TRU', false, NULL, '', 102, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('BHTN_NLD', 'BHTN (1%)', 'KHAU_TRU', false, NULL, '', 103, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('THUE_TNCN', 'Thuế TNCN', 'KHAU_TRU', false, NULL, '', 104, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('PHAT_DI_MUON', 'Phạt đi muộn', 'KHAU_TRU', false, NULL, '', 111, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('PHAT_VE_SOM', 'Phạt về sớm', 'KHAU_TRU', false, NULL, '', 112, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('PHAT_NGHI_KHONG_PHEP', 'Phạt nghỉ không phép', 'KHAU_TRU', false, NULL, '', 113, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('TRU_NGAY_CONG', 'Trừ ngày công', 'KHAU_TRU', false, NULL, '', 114, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, chiu_thue, pham_vi_ap_dung, mo_ta, thu_tu, trang_thai, ngay_tao, ngay_cap_nhat) VALUES ('KHAU_TRU_KHAC', 'Khấu trừ khác', 'KHAU_TRU', false, NULL, '', 120, true, NOW(), NOW()) ON CONFLICT (ma_khoan) DO NOTHING;

-- Cấu hình BHXH
INSERT INTO cau_hinh_bhxh (nam, ty_le_bhxh_nv, ty_le_bhxh_dn, ty_le_bhyt_nv, ty_le_bhyt_dn, ty_le_bhtn_nv, ty_le_bhtn_dn, luong_co_ban_toi_thieu, tran_dong_bhxh, luong_co_so, trang_thai, ngay_tao, ngay_cap_nhat) VALUES (2025, 8, 17.5, 1.5, 3, 1, 1, 4680000, 46800000, 2340000, true, NOW(), NOW()) ON CONFLICT (nam) DO NOTHING;
INSERT INTO cau_hinh_bhxh (nam, ty_le_bhxh_nv, ty_le_bhxh_dn, ty_le_bhyt_nv, ty_le_bhyt_dn, ty_le_bhtn_nv, ty_le_bhtn_dn, luong_co_ban_toi_thieu, tran_dong_bhxh, luong_co_so, trang_thai, ngay_tao, ngay_cap_nhat) VALUES (2026, 8, 17.5, 1.5, 3, 1, 1, 4960000, 49600000, 2480000, true, NOW(), NOW()) ON CONFLICT (nam) DO NOTHING;

-- Cấu hình thuế
INSERT INTO cau_hinh_thue_tncn (nam, giam_tru_ban_than, giam_tru_phu_thuoc, trang_thai, ngay_tao, ngay_cap_nhat) VALUES (2025, 11000000, 4400000, true, NOW(), NOW()) ON CONFLICT (nam) DO NOTHING;
INSERT INTO cau_hinh_thue_tncn (nam, giam_tru_ban_than, giam_tru_phu_thuoc, trang_thai, ngay_tao, ngay_cap_nhat) VALUES (2026, 11000000, 4400000, true, NOW(), NOW()) ON CONFLICT (nam) DO NOTHING;

-- Bậc thuế
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 0), 1, 0, 5000000, 5, 0, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 1), 1, 0, 5000000, 5, 0, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 0), 2, 5000000, 10000000, 10, 250000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 1), 2, 5000000, 10000000, 10, 250000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 0), 3, 10000000, 18000000, 15, 750000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 1), 3, 10000000, 18000000, 15, 750000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 0), 4, 18000000, 32000000, 20, 1650000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 1), 4, 18000000, 32000000, 20, 1650000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 0), 5, 32000000, 52000000, 25, 3250000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 1), 5, 32000000, 52000000, 25, 3250000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 0), 6, 52000000, 80000000, 30, 5850000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 1), 6, 52000000, 80000000, 30, 5850000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 0), 7, 80000000, NULL, 35, 9850000, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO bac_thue_tncn (cau_hinh_thue_id, bac, tu_muc, den_muc, thue_suat, so_tien_tru_nhanh, ngay_tao) VALUES ((SELECT id FROM cau_hinh_thue_tncn ORDER BY id LIMIT 1 OFFSET 1), 7, 80000000, NULL, 35, 9850000, NOW()) ON CONFLICT DO NOTHING;

COMMIT;
