-- HRM-LITE v2 Full Seed Data - Generated: 2026-01-18T04:30:33.518Z

-- 1. PHONG BAN
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('KT', 'Kế toán', 'Phòng Kế toán - Tài chính', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('MKT', 'Marketing', 'Phòng Kinh doanh và Marketing', '08:30', '17:30', 10, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('DH', 'Đơn hàng', 'Phòng Quản lý đơn hàng', '07:30', '16:30', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('KV', 'Kho vận', 'Phòng Kho vận - Logistics', '06:00', '15:00', 10, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('CH', 'Chia hàng', 'Bộ phận Chia hàng', '06:00', '15:00', 10, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('NS', 'Nhân Sự', 'Phòng Nhân Sự', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('SHIP', 'Giao Hàng', NULL, '04:00', '16:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('KE_TOAN', 'Kế Toán', 'Phòng Kế Toán', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('KINH_DOANH', 'Kinh Doanh', 'Phòng Kinh Doanh', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('GIAO_HANG', 'Giao hàng', 'Phòng Giao hàng', '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;
INSERT INTO phong_ban (ma_phong_ban, ten_phong_ban, mo_ta, gio_vao_chuan, gio_ra_chuan, phut_cho_phep_tre, ngay_tao, ngay_cap_nhat) VALUES ('TM', 'Thu mua', NULL, '08:00', '17:00', 5, NOW(), NOW()) ON CONFLICT (ma_phong_ban) DO UPDATE SET ten_phong_ban = EXCLUDED.ten_phong_ban;

-- 2. NHAN VIEN
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0001', 'ĐỖ MỘNG CHÚC ANH', 'nv0001@company.com', NULL, pb.id, 'Thủ quỹ', 6400000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kế Toán' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0002', 'LÊ THÀNH HOÀNG', 'hoang@mail.com', NULL, pb.id, NULL, 5000000, '2026-01-13', 'NGHI_VIEC', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kế Toán' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0003', 'LÂM NHƯ NGỌC', 'nv0003@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kế Toán' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0004', 'PHẠM THÚY DUY', 'duy@mail.com', NULL, pb.id, NULL, 5000000, '2026-01-13', 'NGHI_VIEC', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kế Toán' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0005', 'NGUYỄN ÁI MINH TRIỆU', 'nv0005@company.com', NULL, pb.id, 'Nhân viên', 5500000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kinh Doanh' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0006', 'NGUYỄN THỊ THANH THÚY', 'nv0006@company.com', NULL, pb.id, 'Nhân viên', 5500000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kinh Doanh' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0007', 'PHẠM MINH MẪN', 'nv0007@company.com', NULL, pb.id, 'Nhân viên', 4000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Đơn hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0008', 'LÂM HUỲNH THẠCH QUÝ', 'nv0008@company.com', NULL, pb.id, 'Nhân viên', 4000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Đơn hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0009', 'NGUYỄN ÁI KHANH', 'nv0009@company.com', NULL, pb.id, 'Nhân viên', 4000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Đơn hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0010', 'NGUYỄN VŨ HOÀNG', 'nv0010@company.com', NULL, pb.id, 'Trưởng nhóm', 6000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Đơn hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0011', 'TRẦN THỊ DIỆU LINH', 'nv0011@company.com', NULL, pb.id, 'Nhân viên', 5000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kế Toán' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0012', 'TRẦN HỒ HỮU NHÂN', 'nhan@mail.com', NULL, pb.id, NULL, 5000000, '2026-01-13', 'NGHI_VIEC', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kho vận' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0013', 'TRẦN THỊ TUYẾT LÊ', 'nv0013@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0014', 'DƯ THỊ ƯƠNG', 'nv0014@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0015', 'SƠN THỊ NGỌC HUYỀN', 'nv0015@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0016', 'VÕ THỊ BÍCH DUNG', 'nv0016@company.com', NULL, pb.id, 'Quản Lý', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kho vận' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0017', 'TRẦN THỊ THANH HƯƠNG', 'nv0017@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0018', 'TRẦN THỊ NGỌC THANH', 'nv0018@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0019', 'BÙI THỊ ÁI VÂN', 'nv0019@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0020', 'NGUYỄN THỊ THU', 'nv0020@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0021', 'PHẠM THỊ MINH', 'nv0021@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0022', 'CHÂU THỊ BÉ', 'be@mail.com', NULL, pb.id, NULL, 5000000, '2026-01-13', 'NGHI_VIEC', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0023', 'NGUYỄN NGỌC KIM VĂN', 'van@mail.com', NULL, pb.id, NULL, 5000000, '2026-01-13', 'NGHI_VIEC', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0024', 'LÊ THỊ THÙY TRANG', 'nv0024@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0025', 'NGUYỄN LÝ HỒNG NGỌC', 'nv0025@company.com', NULL, pb.id, 'Nhân viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0026', 'NGUYỄN NHẬT TUẤN', 'nv0026@company.com', NULL, pb.id, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Giao hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0027', 'PHẠM NGỌC AN', 'nv0027@company.com', NULL, pb.id, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Giao hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0028', 'HOÀNG HÙNG', 'nv0028@company.com', NULL, pb.id, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Giao hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0029', 'TRẦN ĐỨC TÚ', 'nv0029@company.com', NULL, pb.id, 'Nhân viên', 4500000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Giao hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0030', 'TRẦN QUỐC VŨ', 'nv0030@company.com', NULL, pb.id, 'Nhân viên', 5500000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Thu mua' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0032', 'NGUYỄN THÀNH BẢO', 'nv0032@company.com', NULL, pb.id, 'Nhân Viên', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Kho vận' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0033', 'LÝ VĂN HÒA', 'nv0033@company.com', NULL, pb.id, 'Nhân viên', 4500000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Giao hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0034', 'HUỲNH PHƯỚC HẢI', 'nv0034@company.com', NULL, pb.id, 'Nhân viên', 4500000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Giao hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0035', 'TRẦN THỊ ÁI NHI', 'nv0035@company.com', NULL, pb.id, 'Học việc', 3500000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Marketing' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0036', 'TRƯƠNG MỸ DUYÊN', 'nv0036@company.com', NULL, pb.id, 'Học việc', 3500000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Marketing' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0037', 'LÊ PHẠM HÀ', 'nv0037@company.com', NULL, pb.id, 'Sơ chế', 4550000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Chia hàng' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0038', 'PHẠM VĂN HÙNG', 'nv0038@company.com', NULL, pb.id, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Thu mua' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;
INSERT INTO nhan_vien (ma_nhan_vien, ho_ten, email, so_dien_thoai, phong_ban_id, chuc_vu, luong_co_ban, ngay_vao_lam, trang_thai, ngay_tao, ngay_cap_nhat) SELECT 'NV0039', 'HOÀNG TỬ LẬP', 'nv0039@company.com', NULL, pb.id, 'Nhân viên', 6000000, '2026-01-13', 'DANG_LAM', NOW(), NOW() FROM phong_ban pb WHERE pb.ten_phong_ban = 'Thu mua' ON CONFLICT (ma_nhan_vien) DO UPDATE SET ho_ten = EXCLUDED.ho_ten, luong_co_ban = EXCLUDED.luong_co_ban;

-- 3. KHOAN LUONG
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('LUONG_CO_BAN', 'Lương cơ bản', 'THU_NHAP', 'LUONG_THANG_CO_DINH', true, 1, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('PHU_CAP_XANG_XE', 'Phụ cấp xăng xe', 'THU_NHAP', 'THEO_NGAY_CONG', false, 2, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('PHU_CAP_DIEN_THOAI', 'Phụ cấp điện thoại', 'THU_NHAP', 'THEO_NGAY_CONG', false, 3, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('HO_TRO_AN_CA', 'Hỗ trợ ăn ca', 'THU_NHAP', 'THEO_NGAY_CONG', false, 4, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('HO_TRO_CHUYEN_CAN', 'Hỗ trợ chuyên cần', 'THU_NHAP', 'CHUYEN_CAN_DIEU_KIEN', false, 5, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('PHU_CAP_CHUC_VU', 'Phụ cấp chức vụ', 'THU_NHAP', 'LUONG_THANG_CO_DINH', true, 6, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('THUONG_KPI', 'Thưởng KPI', 'THU_NHAP', 'LUONG_THANG_CO_DINH', true, 7, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('THUONG_DOANH_SO', 'Thưởng doanh số', 'THU_NHAP', 'LUONG_THANG_CO_DINH', true, 8, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('BHXH_NLD', 'BHXH (8%)', 'KHAU_TRU', 'LUONG_THANG_CO_DINH', false, 101, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('BHYT_NLD', 'BHYT (1.5%)', 'KHAU_TRU', 'LUONG_THANG_CO_DINH', false, 102, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('BHTN_NLD', 'BHTN (1%)', 'KHAU_TRU', 'LUONG_THANG_CO_DINH', false, 103, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('THUE_TNCN', 'Thuế TNCN', 'KHAU_TRU', 'LUONG_THANG_CO_DINH', false, 104, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('PHAT_DI_TRE', 'Phạt đi trễ', 'KHAU_TRU', 'LUONG_THANG_CO_DINH', false, 111, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;
INSERT INTO khoan_luong (ma_khoan, ten_khoan, loai, cach_tinh, chiu_thue, thu_tu, ngay_tao) VALUES ('TRU_UNG_LUONG', 'Trừ ứng lương', 'KHAU_TRU', 'LUONG_THANG_CO_DINH', false, 112, NOW()) ON CONFLICT (ma_khoan) DO NOTHING;

-- 4. LOAI NGHI
INSERT INTO danh_muc_loai_nghi (ma_loai_nghi, ten_loai_nghi, nhom_loai, co_tinh_luong, co_tinh_chuyen_can, thu_tu_hien_thi, ngay_tao) VALUES ('PHEP_NAM', 'Phép năm', 'CO_PHEP', true, true, 1, NOW()) ON CONFLICT (ma_loai_nghi) DO NOTHING;
INSERT INTO danh_muc_loai_nghi (ma_loai_nghi, ten_loai_nghi, nhom_loai, co_tinh_luong, co_tinh_chuyen_can, thu_tu_hien_thi, ngay_tao) VALUES ('NGHI_OM', 'Nghỉ ốm', 'CO_PHEP', true, true, 2, NOW()) ON CONFLICT (ma_loai_nghi) DO NOTHING;
INSERT INTO danh_muc_loai_nghi (ma_loai_nghi, ten_loai_nghi, nhom_loai, co_tinh_luong, co_tinh_chuyen_can, thu_tu_hien_thi, ngay_tao) VALUES ('THAI_SAN', 'Thai sản', 'CO_PHEP', true, true, 3, NOW()) ON CONFLICT (ma_loai_nghi) DO NOTHING;
INSERT INTO danh_muc_loai_nghi (ma_loai_nghi, ten_loai_nghi, nhom_loai, co_tinh_luong, co_tinh_chuyen_can, thu_tu_hien_thi, ngay_tao) VALUES ('VIEC_RIENG', 'Việc riêng có lương', 'CO_PHEP', true, false, 4, NOW()) ON CONFLICT (ma_loai_nghi) DO NOTHING;
INSERT INTO danh_muc_loai_nghi (ma_loai_nghi, ten_loai_nghi, nhom_loai, co_tinh_luong, co_tinh_chuyen_can, thu_tu_hien_thi, ngay_tao) VALUES ('KHONG_LUONG', 'Nghỉ không lương', 'KHONG_LUONG', false, false, 5, NOW()) ON CONFLICT (ma_loai_nghi) DO NOTHING;
INSERT INTO danh_muc_loai_nghi (ma_loai_nghi, ten_loai_nghi, nhom_loai, co_tinh_luong, co_tinh_chuyen_can, thu_tu_hien_thi, ngay_tao) VALUES ('KHONG_PHEP', 'Nghỉ không phép', 'KHONG_PHEP', false, false, 6, NOW()) ON CONFLICT (ma_loai_nghi) DO NOTHING;

-- 5. LOAI YEU CAU
INSERT INTO danh_muc_loai_yeu_cau (ma_loai, ten_loai, nhom, mo_ta, trang_thai, ngay_tao) VALUES ('OT', 'Làm thêm giờ (OT)', 'THOI_GIAN', 'Đơn xin làm thêm giờ', true, NOW()) ON CONFLICT (ma_loai) DO NOTHING;
INSERT INTO danh_muc_loai_yeu_cau (ma_loai, ten_loai, nhom, mo_ta, trang_thai, ngay_tao) VALUES ('TRE_GIO', 'Đi trễ', 'THOI_GIAN', 'Đơn xin đi trễ', true, NOW()) ON CONFLICT (ma_loai) DO NOTHING;
INSERT INTO danh_muc_loai_yeu_cau (ma_loai, ten_loai, nhom, mo_ta, trang_thai, ngay_tao) VALUES ('VE_SOM', 'Về sớm', 'THOI_GIAN', 'Đơn xin về sớm', true, NOW()) ON CONFLICT (ma_loai) DO NOTHING;
INSERT INTO danh_muc_loai_yeu_cau (ma_loai, ten_loai, nhom, mo_ta, trang_thai, ngay_tao) VALUES ('CONG_TAC', 'Công tác', 'DI_CHUYEN', 'Đơn xin công tác', true, NOW()) ON CONFLICT (ma_loai) DO NOTHING;
INSERT INTO danh_muc_loai_yeu_cau (ma_loai, ten_loai, nhom, mo_ta, trang_thai, ngay_tao) VALUES ('WFH', 'Làm việc từ xa', 'DI_CHUYEN', 'Đơn xin làm việc từ xa', true, NOW()) ON CONFLICT (ma_loai) DO NOTHING;

-- 6. CA LAM VIEC
INSERT INTO ca_lam_viec (ma_ca, ten_ca, gio_vao, gio_ra, gio_nghi_trua, het_nghi_trua, trang_thai, ngay_tao) VALUES ('CA_HANH_CHINH', 'Ca hành chính', '08:00', '17:00', '12:00', '13:00', true, NOW()) ON CONFLICT (ma_ca) DO NOTHING;
INSERT INTO ca_lam_viec (ma_ca, ten_ca, gio_vao, gio_ra, gio_nghi_trua, het_nghi_trua, trang_thai, ngay_tao) VALUES ('CA_SANG', 'Ca sáng', '06:00', '14:00', NULL, NULL, true, NOW()) ON CONFLICT (ma_ca) DO NOTHING;
INSERT INTO ca_lam_viec (ma_ca, ten_ca, gio_vao, gio_ra, gio_nghi_trua, het_nghi_trua, trang_thai, ngay_tao) VALUES ('CA_CHIEU', 'Ca chiều', '14:00', '22:00', NULL, NULL, true, NOW()) ON CONFLICT (ma_ca) DO NOTHING;
INSERT INTO ca_lam_viec (ma_ca, ten_ca, gio_vao, gio_ra, gio_nghi_trua, het_nghi_trua, trang_thai, ngay_tao) VALUES ('CA_KHO', 'Ca kho vận', '06:00', '15:00', '11:00', '11:30', true, NOW()) ON CONFLICT (ma_ca) DO NOTHING;
INSERT INTO ca_lam_viec (ma_ca, ten_ca, gio_vao, gio_ra, gio_nghi_trua, het_nghi_trua, trang_thai, ngay_tao) VALUES ('CA_GIAO_HANG', 'Ca giao hàng', '04:00', '12:00', NULL, NULL, true, NOW()) ON CONFLICT (ma_ca) DO NOTHING;

-- 7. TAI KHOAN NHAN VIEN
INSERT INTO nguoi_dung (ten_dang_nhap, mat_khau, email, ho_ten, nhan_vien_id, trang_thai, ngay_tao, ngay_cap_nhat) SELECT LOWER(nv.ma_nhan_vien), '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', COALESCE(nv.email, LOWER(nv.ma_nhan_vien) || '@company.com'), nv.ho_ten, nv.id, 'HOAT_DONG', NOW(), NOW() FROM nhan_vien nv WHERE nv.trang_thai = 'DANG_LAM' AND NOT EXISTS (SELECT 1 FROM nguoi_dung nd WHERE nd.nhan_vien_id = nv.id) ON CONFLICT (ten_dang_nhap) DO NOTHING;

-- 7.1. GAN VAI TRO EMPLOYEE
INSERT INTO nguoi_dung_vai_tro (nguoi_dung_id, vai_tro_id, tu_ngay, ngay_tao) SELECT nd.id, vt.id, NOW(), NOW() FROM nguoi_dung nd CROSS JOIN vai_tro vt WHERE vt.ma_vai_tro = 'EMPLOYEE' AND nd.nhan_vien_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM nguoi_dung_vai_tro ndvt WHERE ndvt.nguoi_dung_id = nd.id AND ndvt.vai_tro_id = vt.id);

-- 7.2. GAN VAI TRO MANAGER
INSERT INTO nguoi_dung_vai_tro (nguoi_dung_id, vai_tro_id, tu_ngay, ngay_tao) SELECT nd.id, vt.id, NOW(), NOW() FROM nguoi_dung nd JOIN nhan_vien nv ON nd.nhan_vien_id = nv.id CROSS JOIN vai_tro vt WHERE vt.ma_vai_tro = 'MANAGER' AND (nv.chuc_vu ILIKE '%Trưởng%' OR nv.chuc_vu ILIKE '%Quản lý%' OR nv.chuc_vu ILIKE '%Manager%') AND NOT EXISTS (SELECT 1 FROM nguoi_dung_vai_tro ndvt WHERE ndvt.nguoi_dung_id = nd.id AND ndvt.vai_tro_id = vt.id);

-- 8. LICH PHAN CA
INSERT INTO lich_phan_ca (ten_lich, thang, nam, trang_thai, ngay_tao) VALUES ('Lịch phân ca tháng 1/2026', 1, 2026, 'DA_XUAT_BAN', NOW()) ON CONFLICT DO NOTHING;

-- 8.1. PHAN CA CHI TIET
INSERT INTO lich_phan_ca_chi_tiet (lich_phan_ca_id, nhan_vien_id, ca_lam_viec_id, ngay_lam_viec, ngay_tao) SELECT lpc.id, nv.id, CASE WHEN pb.ma_phong_ban IN ('KV', 'CH') THEN (SELECT id FROM ca_lam_viec WHERE ma_ca = 'CA_KHO' LIMIT 1) WHEN pb.ma_phong_ban IN ('SHIP', 'GIAO_HANG') THEN (SELECT id FROM ca_lam_viec WHERE ma_ca = 'CA_GIAO_HANG' LIMIT 1) ELSE (SELECT id FROM ca_lam_viec WHERE ma_ca = 'CA_HANH_CHINH' LIMIT 1) END, d::date, NOW() FROM nhan_vien nv JOIN phong_ban pb ON nv.phong_ban_id = pb.id CROSS JOIN lich_phan_ca lpc CROSS JOIN generate_series('2026-01-01'::date, '2026-01-31'::date, '1 day'::interval) d WHERE nv.trang_thai = 'DANG_LAM' AND lpc.thang = 1 AND lpc.nam = 2026 AND EXTRACT(DOW FROM d::date) NOT IN (0) ON CONFLICT DO NOTHING;

-- 9. CHAM CONG
INSERT INTO cham_cong (thang, nam, trang_thai, ngay_tao) VALUES (1, 2026, 'DANG_MO', NOW()) ON CONFLICT DO NOTHING;

-- 9.1. CHI TIET CHAM CONG
INSERT INTO chi_tiet_cham_cong (cham_cong_id, nhan_vien_id, ca_lam_viec_id, ngay_cham_cong, gio_vao, gio_ra, trang_thai, phut_di_tre, phut_ve_som, gio_lam_thuc_te, ngay_tao) SELECT cc.id, nv.id, clv.id, d::date, (clv.gio_vao::time + (floor(random() * 20 - 5) || ' minutes')::interval)::time, (clv.gio_ra::time + (floor(random() * 40 - 10) || ' minutes')::interval)::time, CASE WHEN random() < 0.05 THEN 'VANG_MAT' WHEN random() < 0.15 THEN 'DI_TRE' ELSE 'DU_CONG' END, CASE WHEN random() < 0.15 THEN floor(random() * 30 + 5)::int ELSE 0 END, CASE WHEN random() < 0.05 THEN floor(random() * 20)::int ELSE 0 END, 8.0, NOW() FROM nhan_vien nv JOIN phong_ban pb ON nv.phong_ban_id = pb.id CROSS JOIN cham_cong cc CROSS JOIN ca_lam_viec clv CROSS JOIN generate_series('2026-01-02'::date, '2026-01-17'::date, '1 day'::interval) d WHERE nv.trang_thai = 'DANG_LAM' AND cc.thang = 1 AND cc.nam = 2026 AND clv.ma_ca = CASE WHEN pb.ma_phong_ban IN ('KV', 'CH') THEN 'CA_KHO' WHEN pb.ma_phong_ban IN ('SHIP', 'GIAO_HANG') THEN 'CA_GIAO_HANG' ELSE 'CA_HANH_CHINH' END AND EXTRACT(DOW FROM d::date) NOT IN (0) ON CONFLICT DO NOTHING;

-- 10. DON NGHI PHEP
INSERT INTO don_nghi_phep (nhan_vien_id, loai_nghi_id, tu_ngay, den_ngay, so_ngay, ly_do, trang_thai, ngay_tao) SELECT nv.id, ln.id, '2026-01-20'::date, '2026-01-21'::date, 2, 'Nghỉ phép giải quyết việc gia đình', 'NHAP', NOW() FROM nhan_vien nv CROSS JOIN danh_muc_loai_nghi ln WHERE nv.ma_nhan_vien IN ('NV0005', 'NV0007', 'NV0010') AND ln.ma_loai_nghi = 'PHEP_NAM' AND nv.trang_thai = 'DANG_LAM' ON CONFLICT DO NOTHING;
INSERT INTO don_nghi_phep (nhan_vien_id, loai_nghi_id, tu_ngay, den_ngay, so_ngay, ly_do, trang_thai, ngay_gui_duyet, ngay_duyet, ngay_tao) SELECT nv.id, ln.id, '2026-01-08'::date, '2026-01-08'::date, 1, 'Nghỉ ốm đột xuất', 'DA_DUYET', '2026-01-07'::timestamp, '2026-01-07'::timestamp, NOW() FROM nhan_vien nv CROSS JOIN danh_muc_loai_nghi ln WHERE nv.ma_nhan_vien IN ('NV0003', 'NV0015') AND ln.ma_loai_nghi = 'NGHI_OM' AND nv.trang_thai = 'DANG_LAM' ON CONFLICT DO NOTHING;

-- 11. DON YEU CAU
INSERT INTO don_yeu_cau (nhan_vien_id, loai_yeu_cau_id, ngay_ap_dung, gio_bat_dau, gio_ket_thuc, ly_do, trang_thai, ngay_tao) SELECT nv.id, ly.id, '2026-01-15'::date, '17:00'::time, '20:00'::time, 'Làm thêm giờ hoàn thành đơn hàng gấp', 'NHAP', NOW() FROM nhan_vien nv CROSS JOIN danh_muc_loai_yeu_cau ly WHERE nv.ma_nhan_vien IN ('NV0007', 'NV0008', 'NV0009') AND ly.ma_loai = 'OT' AND nv.trang_thai = 'DANG_LAM' ON CONFLICT DO NOTHING;
INSERT INTO don_yeu_cau (nhan_vien_id, loai_yeu_cau_id, ngay_ap_dung, gio_bat_dau, gio_ket_thuc, ly_do, trang_thai, ngay_duyet_1, ngay_tao) SELECT nv.id, ly.id, '2026-01-10'::date, '08:00'::time, '09:00'::time, 'Đi khám bệnh buổi sáng', 'DA_DUYET_1', '2026-01-09'::timestamp, NOW() FROM nhan_vien nv CROSS JOIN danh_muc_loai_yeu_cau ly WHERE nv.ma_nhan_vien = 'NV0001' AND ly.ma_loai = 'TRE_GIO' AND nv.trang_thai = 'DANG_LAM' ON CONFLICT DO NOTHING;

-- 12. BANG LUONG
INSERT INTO bang_luong (thang, nam, trang_thai, ngay_tao, ngay_chot) VALUES (12, 2025, 'DA_CHOT', NOW(), '2026-01-05'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO chi_tiet_bang_luong (bang_luong_id, nhan_vien_id, luong_co_ban, ngay_cong_thuc_te, ngay_cong_chuan, tong_thu_nhap, tong_khau_tru, thuc_linh, ngay_tao) SELECT bl.id, nv.id, nv.luong_co_ban, 22, 26, nv.luong_co_ban + 500000, nv.luong_co_ban * 0.105, nv.luong_co_ban + 500000 - nv.luong_co_ban * 0.105, NOW() FROM nhan_vien nv CROSS JOIN bang_luong bl WHERE nv.trang_thai = 'DANG_LAM' AND bl.thang = 12 AND bl.nam = 2025 ON CONFLICT DO NOTHING;
INSERT INTO bang_luong (thang, nam, trang_thai, ngay_tao) VALUES (1, 2026, 'DANG_MO', NOW()) ON CONFLICT DO NOTHING;

-- 13. THONG BAO
INSERT INTO thong_bao (nguoi_nhan_id, tieu_de, noi_dung, loai, da_doc, ngay_tao) SELECT nd.id, 'Chào mừng đến HRM-Lite v2', 'Hệ thống quản lý nhân sự HRM-Lite phiên bản 2 đã sẵn sàng!', 'HE_THONG', false, NOW() FROM nguoi_dung nd WHERE nd.ten_dang_nhap = 'admin';
INSERT INTO thong_bao (nguoi_nhan_id, tieu_de, noi_dung, loai, da_doc, ngay_tao) SELECT nd.id, 'Phiếu lương tháng 12/2025', 'Phiếu lương tháng 12/2025 đã sẵn sàng.', 'LUONG', false, NOW() FROM nguoi_dung nd WHERE nd.nhan_vien_id IS NOT NULL;

-- 14. PHU CAP NHAN VIEN
INSERT INTO phu_cap_nhan_vien (nhan_vien_id, khoan_luong_id, gia_tri, tu_ngay, trang_thai, ngay_tao) SELECT nv.id, kl.id, 300000, '2026-01-01'::date, 'DANG_AP_DUNG', NOW() FROM nhan_vien nv CROSS JOIN khoan_luong kl WHERE nv.trang_thai = 'DANG_LAM' AND kl.ma_khoan = 'PHU_CAP_XANG_XE' ON CONFLICT DO NOTHING;
INSERT INTO phu_cap_nhan_vien (nhan_vien_id, khoan_luong_id, gia_tri, tu_ngay, trang_thai, ngay_tao) SELECT nv.id, kl.id, 30000, '2026-01-01'::date, 'DANG_AP_DUNG', NOW() FROM nhan_vien nv CROSS JOIN khoan_luong kl WHERE nv.trang_thai = 'DANG_LAM' AND kl.ma_khoan = 'HO_TRO_AN_CA' ON CONFLICT DO NOTHING;
INSERT INTO phu_cap_nhan_vien (nhan_vien_id, khoan_luong_id, gia_tri, tu_ngay, trang_thai, ngay_tao) SELECT nv.id, kl.id, 1000000, '2026-01-01'::date, 'DANG_AP_DUNG', NOW() FROM nhan_vien nv CROSS JOIN khoan_luong kl WHERE (nv.chuc_vu ILIKE '%Trưởng%' OR nv.chuc_vu ILIKE '%Quản lý%') AND nv.trang_thai = 'DANG_LAM' AND kl.ma_khoan = 'PHU_CAP_CHUC_VU' ON CONFLICT DO NOTHING;

-- 15. GEOFENCE
INSERT INTO cau_hinh_geofence (ten, latitude, longitude, ban_kinh, ap_dung_tat_ca, bat_buoc_gps, chan_ngoai_vung, trang_thai, ngay_tao) VALUES ('Văn phòng chính', 10.8231, 106.6297, 100, true, true, false, true, NOW()) ON CONFLICT DO NOTHING;
INSERT INTO cau_hinh_geofence (ten, latitude, longitude, ban_kinh, ap_dung_tat_ca, bat_buoc_gps, chan_ngoai_vung, trang_thai, ngay_tao) VALUES ('Kho hàng Bình Dương', 10.9803, 106.6520, 200, false, true, false, true, NOW()) ON CONFLICT DO NOTHING;

-- THONG KE
SELECT 'phong_ban' as bang, COUNT(*) as so_luong FROM phong_ban UNION ALL SELECT 'nhan_vien', COUNT(*) FROM nhan_vien UNION ALL SELECT 'nguoi_dung', COUNT(*) FROM nguoi_dung UNION ALL SELECT 'khoan_luong', COUNT(*) FROM khoan_luong UNION ALL SELECT 'ca_lam_viec', COUNT(*) FROM ca_lam_viec UNION ALL SELECT 'lich_phan_ca_chi_tiet', COUNT(*) FROM lich_phan_ca_chi_tiet UNION ALL SELECT 'chi_tiet_cham_cong', COUNT(*) FROM chi_tiet_cham_cong UNION ALL SELECT 'don_nghi_phep', COUNT(*) FROM don_nghi_phep UNION ALL SELECT 'don_yeu_cau', COUNT(*) FROM don_yeu_cau UNION ALL SELECT 'phu_cap_nhan_vien', COUNT(*) FROM phu_cap_nhan_vien ORDER BY bang;